homepage:
    prefix: /
    pattern: /
    defaults: { _controller: NPCoreBundle:Dashboard:index }

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal

np_gallery_gallery:
    resource: "@NPGalleryBundle/Resources/config/routing/gallery.yml"
    prefix:   /gallery
np_gallery_picture:
    resource: "@NPGalleryBundle/Resources/config/routing/picture.yml"
    prefix:   /picture
np_news_news:
    resource: "@NPNewsBundle/Resources/config/routing/news.yml"
    prefix:   /news
np_resources_resources:
    resource: "@NPResourcesBundle/Resources/config/routing/resources.yml"
    prefix:   /resources